---
- hosts: nme
  gather_facts: no
  connection: local
  vars: 
    cli:
      host: 192.168.0.241
      username: justin
      password: cisco
      transport: cli
    remote_user: justin
  tasks:
  - name: test out the ios_config module
    ios_config:
      lines:
        - username ansible password cisco
      provider: "{{ cli }}"
