---

- hosts: local
  vars:
    max_clients: 200
    http_port: 80
  remote_user: root
  tasks:
  - name: ensure apache is at the latest version
    yum: name=httpd state=latest
  - name: write the apache config file
    template: src=/home/justin/templates.j2 dest=/etc/httpd.conf
    notify:
    - restart apache
  - name:
