---
- hosts: nme
  gather_facts: yes
  connection: local
  vars: 
    cli:
      host: 192.168.0.241
      username: justin
      password: cisco
      transport: cli
    remote_user: justin
  tasks:
  - name: test out ios_facts
    ios_facts:
      gather_subset:
        - config
      provider: "{{ cli }}"
