#!/bin/bash

# This script creates a command "mypubip", that returns the public IP address:

# use curl to query checkip.dyndns.org, which returns public IP in the header, then grep for the IP:

mypubip() {
/usr/bin/curl -s checkip.dyndns.org | egrep -o '([[:digit:]]{1,3}\.){3}([[:digit:]]{1,3})'
}

mypubip
